name: Koala Bot 2 CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 18.10.0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: subdir/package-lock.json

      - name: Install Packages
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: subdir/package-lock.json

      - name: Install Packages
        run: npm ci

      - name: Test
        run: npm test -- --ci --reporters=default --reporters=jest-junit

      - name: Report Test Results
        uses: IgnusG/jest-report-action@v2.3.3
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          junit-file: junit.xml

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: subdir/package-lock.json

      - name: Install Packages
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Archive Koala Bot Build
        uses: actions/upload-artifact@v2
        with:
          name: Koala-Bot-2
          path: dist
