name: Koala Bot 2 CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 18.10.0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{runner.os}}-modules-${{hashFiles('package-lock.json')}}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Packages
        run: npm i

      - name: Run ESLint
        run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{runner.os}}-modules-${{hashFiles('package-lock.json')}}

      - name: Install Packages
        run: npm i

      - name: Run Tests with Coverage Report
        run: npm run coverage

      - name: Report Test Results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results
          path: ./reports/jest-junit.xml
          reporter: jest-junit

      - name: Report Coverage
        uses: romeovs/lcov-reporter-action@v0.3.1

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{runner.os}}-modules-${{hashFiles('package-lock.json')}}

      - name: Install Packages
        run: npm i

      - name: Build
        run: npm run build --if-present

      - name: Archive Koala Bot Build
        uses: actions/upload-artifact@v3
        with:
          name: Koala-Bot-2
          path: |
            dist/
            node_modules/
