name: Deploy

on:
  workflow_run:
    workflows: [Test]
    branches: [main]
    types: [completed]

env:
  NODE_VERSION: 18.10.0
  AWS_REGION: ca-central-1
  AWS_LIGHTSAIL_SERVICE_NAME: koala-bot-service

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to ghcr
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/koala-bot:latest
            ghcr.io/${{ github.actor }}/koala-bot:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
      - name: Install AWS Client
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install || true
          aws --version
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "lightsailctl"
          sudo mv "lightsailctl" "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Push and Deploy
        run: |
          service_name=${{ env.AWS_LIGHTSAIL_SERVICE_NAME }}
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${service_name} \
            --label ghcr.io/${{ github.actor }}/koala-bot:latest \
            --image ghcr.io/${{ github.actor }}/koala-bot:latest
          aws lightsail get-container-images --service-name ${service_name} | jq --raw-output ".containerImages[0].image" > image.txt
          jq --arg image $(cat image.txt) '.containers.koala-bot.image = $image' \
          '.containers.koala-bot.environment.DISCORD_BOT_TOKEN = $DISCORD_BOT_TOKEN' \
          '.containers.koala-bot.environment.YOUTUBE_API_KEY = $YOUTUBE_API_KEY' \
          '.containers.koala-bot.environment.CLIENT_ID = $CLIENT_ID' \
          container.template.json > container.json
          aws lightsail create-container-service-deployment --service-name ${service_name} --cli-input-json file://$(pwd)/container.json

  register-commands:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{runner.os}}-modules-${{hashFiles('package-lock.json')}}

      - name: Install Packages
        run: npm i

      - name: Register/Update Commands
        run: npm run register
